In [1]:
# import statements --> SOME OF THESE MAY NOT BE NEEDED
%matplotlib inline 
import numpy as np 

from matplotlib import pyplot as plt 
from matplotlib.cm import get_cmap

from sklearn import neighbors


import umap
import umap.plot
from umap.umap_ import nearest_neighbors
import pandas as pd

import plotly.express as px


import pickle

pd.set_option('display.max_columns', None)

#BRETT NOTEBOOK IMPORTS
from pathlib import Path

from importlib import reload
import utils
reload(utils)
from minisom import MiniSom


# imports from animation_simplified2 notebook
import seaborn as sns
sns.set(style='white', rc={'figure.figsize':(14, 12), 'animation.html': 'html5'})
import os
import copy

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/plot.py:203: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit(nopython=False)

In [2]:
import umapz2

In [3]:
data = pd.read_parquet('df7_maps_250819.parquet')
spec95 = pd.read_parquet('spec95_ugrizyJH_maps_250819.parquet')
data = data.drop(columns=['SOM-1', 'SOM-2', 'UMAP3D-1', 'UMAP3D-2', 'UMAP3D-3'])
spec95 = spec95.drop(columns=['SOM-1', 'SOM-2', 'UMAP3D-1', 'UMAP3D-2', 'UMAP3D-3'])
data = data[~data['ID'].isin(spec95[spec95['specz']<0.01]['ID'])]
spec95 = spec95[spec95['specz']>0.01]
spec95

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,nearest_cat1_ID,nearest_cat1_sep,Id_specz,Id_original,ra_original,dec_original,ra_corrected,dec_corrected,Priority,specz,flag,Confidence_level,survey,compilation_year,public_or_private,Id_COS20_Classic,ra_COS20_Classic,dec_COS20_Classic,Id_COS20_Farmer,ra_COS20_Farmer,dec_COS20_Farmer,Id_COSMOS15,ra_COSMOS15,dec_COSMOS15,Id_COSMOS09,ra_COSMOS09,dec_COSMOS09,photoz,photoz_type
0,535,150.726526,1.795723,0,3.135322,0.004911,0.001979,3.543392,0.005600,0.001707,4.149280,0.006839,0.001707,5.531073,0.006686,0.001311,9.094858,0.011055,0.001310,6.137582,0.023292,0.003891,8.654985,0.055195,0.006917,8.847195,0.061729,0.007971,10.089081,0.037653,0.004077,12.819075,0.017958,0.001854,8.697933,0.024042,0.003679,0.8165,0,NaN,28,1.85,8,1.609000e+08,0.2,1,-20.28363,-21.12927,-21.52369,9.31240,9.27122,9.34644,9.33645,1.23468,-8.087,22.659295,22.526452,22.355068,22.042977,21.503010,21.930007,21.556834,21.532986,21.390371,21.130358,21.551460,0.132843,0.171384,0.312092,0.539966,-0.426997,0.373173,0.023848,57552,0.032255,57552,b'3962782953',150.72652,1.79573,150.72652,1.79573,1,0.82589,4,97,29,2023,1,393505,150.726503,1.795736,535,150.726526,1.795723,334248,150.726575,1.795797,495080,150.72654,1.795808,0.7747,0
1,670,149.730259,1.959835,0,1.941518,0.005379,0.003476,1.863746,0.004178,0.002408,2.359093,0.005581,0.002440,3.347864,0.005832,0.001883,4.712861,0.009339,0.002130,5.044670,0.019908,0.004038,5.936375,0.013675,0.002495,7.337306,0.017588,0.002736,9.483263,0.026426,0.003042,13.707825,0.014322,0.001382,12.806878,0.012845,0.001335,1.1792,0,NaN,30,1.02,10,2.273000e+08,0.3,0,-20.49749,-21.89549,-22.47231,9.79095,9.75692,9.83047,9.80739,1.80017,-7.953,23.179647,23.224033,22.968137,22.588081,22.216789,22.142918,21.966197,21.736158,21.457606,21.057579,21.131392,-0.044386,0.255896,0.380057,0.371292,0.073870,0.176721,0.230038,54582,0.166286,54582,b'3962783555',149.73022,1.95986,149.73022,1.95986,1,1.16549,4,97,29,2023,1,562463,149.730243,1.959851,670,149.730259,1.959835,437916,149.730268,1.959866,816008,149.73022,1.959921,1.1465,0
2,692,149.642181,2.379960,0,1.315313,0.006756,0.006467,4.484449,0.005892,0.001415,13.213070,0.007819,0.000612,24.048380,0.008534,0.000384,35.020987,0.013526,0.000416,40.134805,0.026583,0.000678,66.579523,0.061359,0.000999,98.679499,0.078428,0.000908,133.665136,0.058089,0.000475,81.719072,0.032358,0.000524,83.615927,0.028347,0.000451,0.3269,0,NaN,29,0.29,9,5.000000e+09,0.4,1,-16.72223,-20.57175,-21.94677,10.35539,10.31772,10.39305,10.38281,0.19029,-10.190,23.602427,22.270727,21.097491,20.447285,20.039179,19.891197,19.341648,18.914433,18.584955,19.119191,19.094277,1.331700,1.173237,0.650205,0.408106,0.147982,0.549549,0.427216,134345,0.069986,134345,b'174323',149.64220,2.37996,149.64217,2.37995,1,0.30572,4,97,105,2018,1,1020227,149.642181,2.379958,692,149.642181,2.379960,715344,149.642185,2.379964,1306281,149.64216,2.379982,0.3098,0
3,1143,150.589033,1.889879,0,0.063290,0.003653,0.072636,0.254108,0.004009,0.016990,1.155916,0.005216,0.004662,4.069362,0.005549,0.001476,6.650530,0.009029,0.001461,8.661979,0.019250,0.002276,14.262715,0.022103,0.001680,23.028622,0.020338,0.001009,32.456397,0.027529,0.000926,NaN,NaN,NaN,26.183528,0.044004,0.002237,0.7986,0,NaN,28,0.64,1,2.000000e+09,0.0,0,-16.79230,-21.67922,-22.74348,10.34975,10.31558,10.38392,10.32480,-6.09950,-16.440,26.896659,25.387452,23.742684,22.376184,21.842859,21.555957,21.014494,20.494330,20.121749,NaN,20.354930,1.509207,1.644768,1.366500,0.533325,0.286902,0.541463,0.520164,125270,0.419481,125270,b'VIS3COS-66',150.58907,1.88999,150.58906,1.88997,1,0.80030,4,97,93,2018,1,490953,150.589037,1.889878,1143,150.589033,1.889879,393862,150.589084,1.889884,483526,150.58906,1.889898,0.6834,0
4,1245,149.971382,1.711330,0,1.695707,0.006863,0.005056,1.691740,0.005530,0.003500,2.357181,0.007089,0.003094,3.366750,0.007567,0.002425,5.704886,0.012347,0.002323,6.829482,0.025867,0.003871,9.471108,0.059377,0.006786,13.002449,0.077023,0.006759,18.572509,0.051679,0.003037,29.470112,0.016731,0.000751,28.078737,0.017725,0.000840,1.2540,0,NaN,29,1.09,7,2.600000e+09,0.2,0,-20.53407,-22.57335,-23.39578,10.59188,10.55031,10.64044,10.62809,1.40000,-9.214,23.326623,23.329166,22.969017,22.581973,22.009383,21.814031,21.458998,21.114937,20.727824,20.226546,20.279056,-0.002543,0.360149,0.387045,0.572590,0.195352,0.355033,0.344061,58944,0.154891,58944,b'3962782951',149.97134,1.71132,149.97134,1.71132,1,1.23815,4,97,29,2023,1,306648,149.971385,1.711328,1245,149.971382,1.711330,280616,149.971401,1.711326,362912,149.97138,1.711345,1.2532,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14494,964293,150.197702,1.791536,0,7.815364,0.012754,0.002038,18.310474,0.009038,0.000528,45.964169,0.012306,0.000275,74.019787,0.013086,0.000191,97.404310,0.021407,0.000236,109.393904,0.038414,0.000359,154.071989,0.025450,0.000179,200.484768,0.034710,0.000198,238.176555,0.050933,0.000233,137.774089,0.016902,0.000162,123.599561,0.018025,0.000194,0.3154,0,NaN,30,0.34,9,5.500000e+09,0.1,0,-18.72000,-21.66386,-22.62620,10.65000,10.61600,10.68400,10.61871,0.30000,-10.370,21.667627,20.743251,19.743951,19.226630,18.928555,18.802517,18.430691,18.144797,17.957752,18.552081,18.669958,0.924376,0.999300,0.517321,0.298076,0.126037,0.371826,0.285894,132308,0.194219,132308,b'28436',150.19775,1.79156,150.19772,1.79155,1,0.30882,4,97,105,2018,1,395449,150.197703,1.791550,964293,150.197702,1.791536,333031,150.197736,1.791557,351111,150.19771,1.791548,0.3240,0
14495,964308,150.189166,1.786760,0,0.376955,0.007829,0.025939,1.125239,0.004581,0.004358,4.881146,0.006761,0.001425,16.260245,0.007515,0.000499,27.009426,0.012383,0.000492,32.401518,0.022967,0.000724,51.259633,0.015446,0.000326,72.215790,0.020729,0.000327,94.934133,0.030071,0.000346,116.689012,0.012641,0.000143,77.455344,0.013697,0.000235,0.8244,0,NaN,29,0.68,2,2.300000e+09,0.0,0,-18.47022,-23.15855,-23.98529,11.00000,10.96600,11.03400,10.98945,-0.60000,-11.560,24.959276,23.771888,22.178695,20.872182,20.321212,20.123587,19.625561,19.253420,18.956444,18.732425,19.177372,1.187388,1.593193,1.306513,0.550971,0.197625,0.498025,0.372142,83267,0.197580,83267,b'28041',150.18922,1.78677,150.18919,1.78676,1,0.80880,4,97,56,2021,1,387856,150.189194,1.786747,964308,150.189166,1.786760,329823,150.189228,1.786753,351224,150.18922,1.786748,0.8253,0
14496,964377,149.971501,2.459277,0,0.781867,0.006094,0.009706,4.248786,0.004722,0.001187,16.713592,0.007689,0.000472,31.840775,0.008043,0.000272,42.508116,0.012185,0.000307,51.027704,0.021628,0.000433,77.996092,0.039856,0.000553,113.188162,0.053447,0.000539,141.624981,0.037039,0.000285,73.498912,0.025304,0.000455,58.364998,0.027856,0.000635,0.4349,0,NaN,29,0.32,3,6.500000e+09,0.0,0,-17.31676,-21.65651,-22.77276,10.83808,10.53309,10.88018,10.81345,-0.72385,-11.550,24.167168,22.329338,20.842326,20.142541,19.828820,19.630485,19.169818,18.765497,18.522150,19.234298,19.484619,1.837830,1.487012,0.699785,0.313721,0.198335,0.460667,0.404320,133856,0.034989,133856,b'205505',149.97151,2.45928,149.97148,2.45927,1,0.34094,4,97,105,2018,1,1102606,149.971506,2.459279,964377,149.971501,2.459277,766781,149.971518,2.459271,1271179,149.97149,2.459271,0.3351,0
14497,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,3523,0.114666,3523,b'COSMOS-332',149.92700,2.37619,149.92699,2.37619,1,0.89240,4,97,17,2019,1,1011939,149.926991,2.376210,964392,149.926987,2.376219,710337,149.927012,2.376205,1258212,149.92699,2.376230,0.8716,0
14498,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,125174,0.282336,125174,b'VIS3COS-52',150.44652,2.04202,150.44651,2.04200,1,0.82590,4,97,93,2018,1,649550,150.446489,2.041979,964399,150.446456,2.041975,488671,150.446514,2.041986,729279,150.44652,2.042031,0.7770,0

In [4]:
data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125

In [ ]:
#data = data[~data['ID'].isin(spec95[spec95['specz']<0.01]['ID'])]
#spec95 = spec95[spec95['specz']>0.01]
#spec95

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,nearest_cat1_ID,nearest_cat1_sep,Id_specz,Id_original,ra_original,dec_original,ra_corrected,dec_corrected,Priority,specz,flag,Confidence_level,survey,compilation_year,public_or_private,Id_COS20_Classic,ra_COS20_Classic,dec_COS20_Classic,Id_COS20_Farmer,ra_COS20_Farmer,dec_COS20_Farmer,Id_COSMOS15,ra_COSMOS15,dec_COSMOS15,Id_COSMOS09,ra_COSMOS09,dec_COSMOS09,photoz,photoz_type
0,535,150.726526,1.795723,0,3.135322,0.004911,0.001979,3.543392,0.005600,0.001707,4.149280,0.006839,0.001707,5.531073,0.006686,0.001311,9.094858,0.011055,0.001310,6.137582,0.023292,0.003891,8.654985,0.055195,0.006917,8.847195,0.061729,0.007971,10.089081,0.037653,0.004077,12.819075,0.017958,0.001854,8.697933,0.024042,0.003679,0.8165,0,NaN,28,1.85,8,1.609000e+08,0.2,1,-20.28363,-21.12927,-21.52369,9.31240,9.27122,9.34644,9.33645,1.23468,-8.087,22.659295,22.526452,22.355068,22.042977,21.503010,21.930007,21.556834,21.532986,21.390371,21.130358,21.551460,0.132843,0.171384,0.312092,0.539966,-0.426997,0.373173,0.023848,57552,0.032255,57552,b'3962782953',150.72652,1.79573,150.72652,1.79573,1,0.82589,4,97,29,2023,1,393505,150.726503,1.795736,535,150.726526,1.795723,334248,150.726575,1.795797,495080,150.72654,1.795808,0.7747,0
1,670,149.730259,1.959835,0,1.941518,0.005379,0.003476,1.863746,0.004178,0.002408,2.359093,0.005581,0.002440,3.347864,0.005832,0.001883,4.712861,0.009339,0.002130,5.044670,0.019908,0.004038,5.936375,0.013675,0.002495,7.337306,0.017588,0.002736,9.483263,0.026426,0.003042,13.707825,0.014322,0.001382,12.806878,0.012845,0.001335,1.1792,0,NaN,30,1.02,10,2.273000e+08,0.3,0,-20.49749,-21.89549,-22.47231,9.79095,9.75692,9.83047,9.80739,1.80017,-7.953,23.179647,23.224033,22.968137,22.588081,22.216789,22.142918,21.966197,21.736158,21.457606,21.057579,21.131392,-0.044386,0.255896,0.380057,0.371292,0.073870,0.176721,0.230038,54582,0.166286,54582,b'3962783555',149.73022,1.95986,149.73022,1.95986,1,1.16549,4,97,29,2023,1,562463,149.730243,1.959851,670,149.730259,1.959835,437916,149.730268,1.959866,816008,149.73022,1.959921,1.1465,0
2,692,149.642181,2.379960,0,1.315313,0.006756,0.006467,4.484449,0.005892,0.001415,13.213070,0.007819,0.000612,24.048380,0.008534,0.000384,35.020987,0.013526,0.000416,40.134805,0.026583,0.000678,66.579523,0.061359,0.000999,98.679499,0.078428,0.000908,133.665136,0.058089,0.000475,81.719072,0.032358,0.000524,83.615927,0.028347,0.000451,0.3269,0,NaN,29,0.29,9,5.000000e+09,0.4,1,-16.72223,-20.57175,-21.94677,10.35539,10.31772,10.39305,10.38281,0.19029,-10.190,23.602427,22.270727,21.097491,20.447285,20.039179,19.891197,19.341648,18.914433,18.584955,19.119191,19.094277,1.331700,1.173237,0.650205,0.408106,0.147982,0.549549,0.427216,134345,0.069986,134345,b'174323',149.64220,2.37996,149.64217,2.37995,1,0.30572,4,97,105,2018,1,1020227,149.642181,2.379958,692,149.642181,2.379960,715344,149.642185,2.379964,1306281,149.64216,2.379982,0.3098,0
3,1143,150.589033,1.889879,0,0.063290,0.003653,0.072636,0.254108,0.004009,0.016990,1.155916,0.005216,0.004662,4.069362,0.005549,0.001476,6.650530,0.009029,0.001461,8.661979,0.019250,0.002276,14.262715,0.022103,0.001680,23.028622,0.020338,0.001009,32.456397,0.027529,0.000926,NaN,NaN,NaN,26.183528,0.044004,0.002237,0.7986,0,NaN,28,0.64,1,2.000000e+09,0.0,0,-16.79230,-21.67922,-22.74348,10.34975,10.31558,10.38392,10.32480,-6.09950,-16.440,26.896659,25.387452,23.742684,22.376184,21.842859,21.555957,21.014494,20.494330,20.121749,NaN,20.354930,1.509207,1.644768,1.366500,0.533325,0.286902,0.541463,0.520164,125270,0.419481,125270,b'VIS3COS-66',150.58907,1.88999,150.58906,1.88997,1,0.80030,4,97,93,2018,1,490953,150.589037,1.889878,1143,150.589033,1.889879,393862,150.589084,1.889884,483526,150.58906,1.889898,0.6834,0
4,1245,149.971382,1.711330,0,1.695707,0.006863,0.005056,1.691740,0.005530,0.003500,2.357181,0.007089,0.003094,3.366750,0.007567,0.002425,5.704886,0.012347,0.002323,6.829482,0.025867,0.003871,9.471108,0.059377,0.006786,13.002449,0.077023,0.006759,18.572509,0.051679,0.003037,29.470112,0.016731,0.000751,28.078737,0.017725,0.000840,1.2540,0,NaN,29,1.09,7,2.600000e+09,0.2,0,-20.53407,-22.57335,-23.39578,10.59188,10.55031,10.64044,10.62809,1.40000,-9.214,23.326623,23.329166,22.969017,22.581973,22.009383,21.814031,21.458998,21.114937,20.727824,20.226546,20.279056,-0.002543,0.360149,0.387045,0.572590,0.195352,0.355033,0.344061,58944,0.154891,58944,b'3962782951',149.97134,1.71132,149.97134,1.71132,1,1.23815,4,97,29,2023,1,306648,149.971385,1.711328,1245,149.971382,1.711330,280616,149.971401,1.711326,362912,149.97138,1.711345,1.2532,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14494,964293,150.197702,1.791536,0,7.815364,0.012754,0.002038,18.310474,0.009038,0.000528,45.964169,0.012306,0.000275,74.019787,0.013086,0.000191,97.404310,0.021407,0.000236,109.393904,0.038414,0.000359,154.071989,0.025450,0.000179,200.484768,0.034710,0.000198,238.176555,0.050933,0.000233,137.774089,0.016902,0.000162,123.599561,0.018025,0.000194,0.3154,0,NaN,30,0.34,9,5.500000e+09,0.1,0,-18.72000,-21.66386,-22.62620,10.65000,10.61600,10.68400,10.61871,0.30000,-10.370,21.667627,20.743251,19.743951,19.226630,18.928555,18.802517,18.430691,18.144797,17.957752,18.552081,18.669958,0.924376,0.999300,0.517321,0.298076,0.126037,0.371826,0.285894,132308,0.194219,132308,b'28436',150.19775,1.79156,150.19772,1.79155,1,0.30882,4,97,105,2018,1,395449,150.197703,1.791550,964293,150.197702,1.791536,333031,150.197736,1.791557,351111,150.19771,1.791548,0.3240,0
14495,964308,150.189166,1.786760,0,0.376955,0.007829,0.025939,1.125239,0.004581,0.004358,4.881146,0.006761,0.001425,16.260245,0.007515,0.000499,27.009426,0.012383,0.000492,32.401518,0.022967,0.000724,51.259633,0.015446,0.000326,72.215790,0.020729,0.000327,94.934133,0.030071,0.000346,116.689012,0.012641,0.000143,77.455344,0.013697,0.000235,0.8244,0,NaN,29,0.68,2,2.300000e+09,0.0,0,-18.47022,-23.15855,-23.98529,11.00000,10.96600,11.03400,10.98945,-0.60000,-11.560,24.959276,23.771888,22.178695,20.872182,20.321212,20.123587,19.625561,19.253420,18.956444,18.732425,19.177372,1.187388,1.593193,1.306513,0.550971,0.197625,0.498025,0.372142,83267,0.197580,83267,b'28041',150.18922,1.78677,150.18919,1.78676,1,0.80880,4,97,56,2021,1,387856,150.189194,1.786747,964308,150.189166,1.786760,329823,150.189228,1.786753,351224,150.18922,1.786748,0.8253,0
14496,964377,149.971501,2.459277,0,0.781867,0.006094,0.009706,4.248786,0.004722,0.001187,16.713592,0.007689,0.000472,31.840775,0.008043,0.000272,42.508116,0.012185,0.000307,51.027704,0.021628,0.000433,77.996092,0.039856,0.000553,113.188162,0.053447,0.000539,141.624981,0.037039,0.000285,73.498912,0.025304,0.000455,58.364998,0.027856,0.000635,0.4349,0,NaN,29,0.32,3,6.500000e+09,0.0,0,-17.31676,-21.65651,-22.77276,10.83808,10.53309,10.88018,10.81345,-0.72385,-11.550,24.167168,22.329338,20.842326,20.142541,19.828820,19.630485,19.169818,18.765497,18.522150,19.234298,19.484619,1.837830,1.487012,0.699785,0.313721,0.198335,0.460667,0.404320,133856,0.034989,133856,b'205505',149.97151,2.45928,149.97148,2.45927,1,0.34094,4,97,105,2018,1,1102606,149.971506,2.459279,964377,149.971501,2.459277,766781,149.971518,2.459271,1271179,149.97149,2.459271,0.3351,0
14497,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,3523,0.114666,3523,b'COSMOS-332',149.92700,2.37619,149.92699,2.37619,1,0.89240,4,97,17,2019,1,1011939,149.926991,2.376210,964392,149.926987,2.376219,710337,149.927012,2.376205,1258212,149.92699,2.376230,0.8716,0
14498,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,125174,0.282336,125174,b'VIS3COS-52',150.44652,2.04202,150.44651,2.04200,1,0.82590,4,97,93,2018,1,649550,150.446489,2.041979,964399,150.446456,2.041975,488671,150.446514,2.041986,729279,150.44652,2.042031,0.7770,0

In [7]:
# path for saving SOM files
path = '/Users/finianashmead/Desktop/NEWMANGROUP/'
directory = 'path_pck_manhattan'
path_pck = Path(path+directory)

In [7]:
reload(umapz2)

In [10]:
path_pck

PosixPath('/Users/finianashmead/Desktop/NEWMANGROUP/path_pck_manhattan')

In [7]:
n_embeddings = 25
for i in range(n_embeddings):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24

In [ ]:
size=(75,150)
sigma=1
learning_rate=0.8

n_embeddings = 25
for i in range(n_embeddings+1):
    print(i)
    data_i = umapz2.train_som(data, size, sigma, learning_rate, n_iter=2_000_000, rs=i, path_pck=path_pck, metric='manhattan')
    data['SOMrs'+str(i)+'-1'] = data_i['SOM_'+str(size[0])+'_'+str(size[1])+'_s'+str(sigma)+'_lr'+str(learning_rate)+'-1']
    data['SOMrs'+str(i)+'-2'] = data_i['SOM_'+str(size[0])+'_'+str(size[1])+'_s'+str(sigma)+'_lr'+str(learning_rate)+'-2']

In [14]:
#data.to_parquet('som_rs25_maps_manhattan_260509.parquet')

hi

In [18]:
data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,SOMrs0-1,SOMrs0-2,SOMrs1-1,SOMrs1-2,SOMrs2-1,SOMrs2-2,SOMrs3-1,SOMrs3-2,SOMrs4-1,SOMrs4-2,SOMrs5-1,SOMrs5-2,SOMrs6-1,SOMrs6-2,SOMrs7-1,SOMrs7-2,SOMrs8-1,SOMrs8-2,SOMrs9-1,SOMrs9-2,SOMrs10-1,SOMrs10-2,SOMrs11-1,SOMrs11-2,SOMrs12-1,SOMrs12-2,SOMrs13-1,SOMrs13-2,SOMrs14-1,SOMrs14-2,SOMrs15-1,SOMrs15-2,SOMrs16-1,SOMrs16-2,SOMrs17-1,SOMrs17-2,SOMrs18-1,SOMrs18-2,SOMrs19-1,SOMrs19-2,SOMrs20-1,SOMrs20-2,SOMrs21-1,SOMrs21-2,SOMrs22-1,SOMrs22-2,SOMrs23-1,SOMrs23-2,SOMrs24-1,SOMrs24-2,SOMrs25-1,SOMrs25-2
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011,13,62,9,81,24,83,28,96,47,93,46,81,40,87,12,22,39,83,14,76,20,93,47,50,45,90,35,17,2,46,41,83,3,36,19,60,12,69,4,41,39,34,10,15,37,84,44,18,12,13,47,31
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637,11,21,25,31,6,55,32,46,42,37,21,35,31,49,42,53,11,37,7,67,11,91,5,66,47,57,45,5,8,79,47,97,16,42,24,3,18,58,7,79,9,49,5,1,25,77,38,38,43,21,45,10
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847,43,95,46,91,25,95,17,70,5,93,6,96,0,95,36,31,49,24,29,84,46,80,16,51,22,96,4,92,14,1,14,47,12,90,8,94,43,55,29,37,34,7,25,19,3,35,36,72,2,47,28,20
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585,29,93,39,83,47,17,6,43,7,81,40,46,22,4,15,14,46,5,34,74,37,53,47,23,41,90,9,28,15,7,32,48,28,68,37,62,13,48,38,99,46,24,9,96,11,69,46,9,22,24,9,95
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305,44,87,22,59,45,78,23,63,14,78,7,81,25,66,33,12,41,35,39,61,42,57,37,9,29,86,6,40,16,73,30,17,42,50,43,9,46,30,45,95,45,13,2,92,10,23,40,63,41,76,22,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,2,35,20,89,33,45,47,80,15,51,35,86,2,63,11,13,23,67,38,76,43,19,9,98,4,93,1,23,0,17,33,54,14,83,45,64,7,34,6,56,37,77,35,13,42,58,30,89,14,22,41,39
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779,44,76,46,82,40,54,39,89,1,56,2,4,49,65,2,74,34,9,37,19,35,74,44,92,33,32,5,85,4,1,34,82,13,99,29,99,46,43,38,72,27,78,12,59,26,69,29,65,39,64,22,15
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,4,0,33,98,28,72,43,73,4,33,25,57,19,73,37,73,3,17,45,83,23,56,42,2,8,84,45,60,36,83,31,8,17,62,46,48,33,28,19,40,45,3,16,23,15,6,48,67,16,27,1,26
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295,5,11,13,30,5,33,10,9,26,43,36,73,30,85,13,27,6,32,28,50,24,88,14,92,46,68,35,47,37,9,36,88,7,34,21,53,25,67,19,96,35,43,38,90,34,92,25,24,22,47,39,91
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125,23,79,38,32,11,77,1,14,27,0,24,41,47,27,18,3,20,33,7,56,1,51,9,64,17,30,29,9,44,86,45,11,25,43,34,44,32,66,44,10,28,51,14,53,41,47,16,22,1,52,31,7

In [8]:
path_pck

PosixPath('/Users/finianashmead/Desktop/NEWMANGROUP/path_pck_manhattan')

In [ ]:
#sizes=[(8,16), (12,24), (18,36), (25,50), (35,70), (50,100), (75,150)]
sizes=[(69,138),(75,150),(80,160)]

sigmas = [0.85, 1, 1.15]
learning_rates = [0.68, 0.8, 0.92]

data_soms = umapz2.train_soms(data, sizes, sigmas, learning_rates, n_iter=2_000_000, rs=42, path_pck=path_pck, metric='manhattan')

In [10]:
data_soms

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,SOM_69_138_s0.85_lr0.68-1,SOM_69_138_s0.85_lr0.68-2,SOM_69_138_s0.85_lr0.8-1,SOM_69_138_s0.85_lr0.8-2,SOM_69_138_s0.85_lr0.92-1,SOM_69_138_s0.85_lr0.92-2,SOM_69_138_s1_lr0.68-1,SOM_69_138_s1_lr0.68-2,SOM_69_138_s1_lr0.8-1,SOM_69_138_s1_lr0.8-2,SOM_69_138_s1_lr0.92-1,SOM_69_138_s1_lr0.92-2,SOM_69_138_s1.15_lr0.68-1,SOM_69_138_s1.15_lr0.68-2,SOM_69_138_s1.15_lr0.8-1,SOM_69_138_s1.15_lr0.8-2,SOM_69_138_s1.15_lr0.92-1,SOM_69_138_s1.15_lr0.92-2,SOM_75_150_s0.85_lr0.68-1,SOM_75_150_s0.85_lr0.68-2,SOM_75_150_s0.85_lr0.8-1,SOM_75_150_s0.85_lr0.8-2,SOM_75_150_s0.85_lr0.92-1,SOM_75_150_s0.85_lr0.92-2,SOM_75_150_s1_lr0.68-1,SOM_75_150_s1_lr0.68-2,SOM_75_150_s1_lr0.8-1,SOM_75_150_s1_lr0.8-2,SOM_75_150_s1_lr0.92-1,SOM_75_150_s1_lr0.92-2,SOM_75_150_s1.15_lr0.68-1,SOM_75_150_s1.15_lr0.68-2,SOM_75_150_s1.15_lr0.8-1,SOM_75_150_s1.15_lr0.8-2,SOM_75_150_s1.15_lr0.92-1,SOM_75_150_s1.15_lr0.92-2,SOM_80_160_s0.85_lr0.68-1,SOM_80_160_s0.85_lr0.68-2,SOM_80_160_s0.85_lr0.8-1,SOM_80_160_s0.85_lr0.8-2,SOM_80_160_s0.85_lr0.92-1,SOM_80_160_s0.85_lr0.92-2,SOM_80_160_s1_lr0.68-1,SOM_80_160_s1_lr0.68-2,SOM_80_160_s1_lr0.8-1,SOM_80_160_s1_lr0.8-2,SOM_80_160_s1_lr0.92-1,SOM_80_160_s1_lr0.92-2,SOM_80_160_s1.15_lr0.68-1,SOM_80_160_s1.15_lr0.68-2,SOM_80_160_s1.15_lr0.8-1,SOM_80_160_s1.15_lr0.8-2,SOM_80_160_s1.15_lr0.92-1,SOM_80_160_s1.15_lr0.92-2
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011,0,129,0,12,13,80,43,11,28,10,43,10,47,116,56,53,34,124,62,69,74,29,38,8,56,125,53,128,64,68,53,110,11,147,13,126,43,80,12,108,4,95,43,89,69,27,3,100,48,89,27,156,67,99
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637,35,25,26,6,59,49,30,2,60,52,46,99,21,4,38,7,31,16,29,111,70,131,24,26,26,18,29,63,48,62,61,127,45,65,34,56,74,19,28,84,24,96,16,88,16,91,20,83,16,84,44,105,77,17
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847,45,99,59,8,45,90,4,130,61,113,59,3,61,78,68,3,2,104,51,33,50,49,41,133,50,136,48,135,33,141,48,130,26,144,23,146,61,15,67,110,45,98,57,104,79,109,8,82,34,0,77,127,48,119
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585,5,19,64,90,46,16,55,89,56,75,58,87,63,88,44,20,29,123,32,138,56,109,74,64,61,109,55,149,69,109,4,36,19,135,5,140,76,114,61,4,30,119,40,7,38,133,28,121,39,123,51,128,25,93
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305,2,10,27,129,39,5,59,88,66,90,3,132,20,134,5,120,48,5,23,145,49,28,51,4,58,140,61,136,13,144,67,144,74,142,73,106,46,118,65,11,59,13,66,20,50,109,67,122,57,18,14,1,23,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,45,20,42,16,54,90,39,118,29,106,3,14,64,14,47,132,59,87,64,70,42,40,30,66,67,51,48,42,48,43,64,89,3,144,49,140,55,45,43,13,33,77,54,92,28,122,44,19,1,97,38,123,76,101
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779,4,80,22,104,34,15,12,105,14,106,63,9,54,0,61,16,12,98,16,34,4,33,36,136,54,5,29,33,63,77,35,149,13,61,60,46,50,44,57,136,71,108,12,17,5,19,35,74,0,11,51,93,54,132
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,8,10,8,15,39,135,1,57,10,11,65,46,37,133,9,134,58,73,8,52,50,59,56,67,56,60,71,70,6,45,69,64,71,60,27,114,63,91,6,115,20,144,17,148,60,87,13,142,10,150,62,120,13,144
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295,23,126,58,118,60,113,62,44,44,102,38,119,50,54,50,50,14,19,3,132,5,124,35,21,12,132,44,26,56,73,36,56,31,79,45,58,60,111,18,62,71,102,3,113,34,86,40,35,75,52,26,79,3,17
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125,30,134,43,80,53,124,19,114,25,131,47,129,34,69,46,12,2,120,30,3,51,104,14,120,11,9,15,113,6,113,67,24,55,101,36,104,34,106,9,67,76,123,29,142,11,111,68,81,55,150,59,104,25,138

In [11]:
#data_soms.to_parquet('som_embeddings_manhattan_260507.parquet')

In [18]:
splits_soms = umapz2.data_split(photcat=data_soms, speccat=spec95, valid_size=len(spec95), rs=41)
splits_soms.keys()

dict_keys(['valid', 'train_lp', 'test_lp', 'train_spec', 'test_spec'])

In [ ]:
sizes=[(8,16), (12,24), (18,36), (25,50), (35,70), (50,100), (75,150)]
#sizes=[(75,)]

sigmas = [0.5, 1, 2, 4]
learning_rates = [0.8]

for size in sizes:
        n_som_xy = size
        for sigma in sigmas:
            for lr in learning_rates:
                map = 'SOM_'+str(n_som_xy[0])+'_'+str(n_som_xy[1])+'_s'+str(sigma)+'_lr'+str(lr)
                umapz2.plot_som_valid(full_df=data_soms, valid_df=splits_soms['valid'], 
                                      map=map, size=size, 
                                      filename=map+'_n2M_manhattan_260507.png');

In [9]:
#data_soms.to_parquet('som_embeddings_manhattan_260507.parquet')

data_soms

In [10]:
#data_soms.to_parquet('som_embeddings2M_260409.parquet')

In [7]:
data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125

In [8]:
# loop over n_neighbors hyperparameter arguments (nn_hps) to generate multiple embeddings

#nn_hps = [55, 60, 65, 70, 75, 80, 85]
nn_hps = [50, 55, 60, 65, 70, 75, 80, 85, 90]
#nn_hps = [68, 80, 92]

for nn_hp in nn_hps:
    emb_i = umap.UMAP(n_neighbors=nn_hp, min_dist=0.0, metric='manhattan', n_components=3, random_state=41, densmap=False).fit(data[['u-g', 'g-r', 'r-i', 'i-z', 'z-y', 'y-J', 'J-H']])
    data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
    data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
    data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
/var/folders/zr/5945lkps2z573rnydx977g7m0000gn/T/ipykernel_4284/303788065.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]

In [26]:
#data.to_parquet('som_umap_uncbudget_maps_260415.parquet')

In [9]:
data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,UMAPnn50-1,UMAPnn50-2,UMAPnn50-3,UMAPnn55-1,UMAPnn55-2,UMAPnn55-3,UMAPnn60-1,UMAPnn60-2,UMAPnn60-3,UMAPnn65-1,UMAPnn65-2,UMAPnn65-3,UMAPnn70-1,UMAPnn70-2,UMAPnn70-3,UMAPnn75-1,UMAPnn75-2,UMAPnn75-3,UMAPnn80-1,UMAPnn80-2,UMAPnn80-3,UMAPnn85-1,UMAPnn85-2,UMAPnn85-3,UMAPnn90-1,UMAPnn90-2,UMAPnn90-3
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011,-1.033182,3.720988,-1.388137,-0.959336,3.825539,-1.231575,-0.881290,3.796339,-1.209693,-0.870086,3.704909,-0.993322,-0.741683,3.692303,-0.950502,-0.785397,3.743953,-0.928493,-0.760679,3.647432,-0.850287,-0.661774,3.742576,-0.734830,-0.621733,3.676099,-0.746140
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637,0.766996,6.048308,-1.416872,0.806598,6.124864,-1.232763,0.871471,6.029686,-1.179094,0.866591,6.002512,-1.039919,0.968271,5.938120,-1.001814,0.977910,5.954481,-0.898991,0.951395,5.896547,-0.895896,1.066993,5.960493,-0.719571,1.100952,5.834060,-0.780278
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847,0.555235,4.140800,9.900080,0.633083,4.132921,10.070456,0.533604,4.124071,10.108575,0.624591,4.132191,10.229904,0.640105,4.060228,10.181063,0.650863,4.067042,10.252739,0.659285,4.106952,10.281441,0.690439,4.038807,10.390600,0.633836,4.054846,10.377823
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585,-1.945760,-0.692630,4.997665,-1.949973,-0.647341,4.967613,-1.864844,-0.585670,5.083677,-1.807278,-0.580344,5.212979,-1.836826,-0.611205,5.174289,-1.759441,-0.570882,5.230515,-1.715026,-0.590169,5.356193,-1.660230,-0.564810,5.354786,-1.729631,-0.553385,5.305346
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305,-0.790977,-0.075492,6.492111,-0.771743,-0.142162,6.456462,-0.777141,-0.047835,6.610816,-0.724739,-0.024433,6.746705,-0.739287,-0.050950,6.726170,-0.718467,-0.017266,6.760951,-0.675153,-0.009987,6.850944,-0.615032,0.017529,6.890368,-0.612567,0.021912,6.880016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,-1.525141,-0.211663,2.291117,-1.475640,-0.103305,2.345048,-1.444229,-0.080627,2.480518,-1.367823,-0.111595,2.604275,-1.315133,-0.139675,2.575526,-1.338057,-0.083955,2.731002,-1.248769,-0.069407,2.771871,-1.231487,-0.086546,2.838809,-1.287613,-0.086784,2.889730
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779,2.087984,3.162211,8.243819,2.118040,3.065669,8.305524,2.034119,3.145387,8.449854,2.150255,3.124451,8.451149,2.107948,3.061284,8.482687,2.106723,3.110953,8.568293,2.094156,3.141465,8.625670,2.138883,3.119044,8.667297,2.080029,3.072480,8.689934
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,-2.423579,1.162836,-0.435563,-2.363719,1.229874,-0.350366,-2.225241,1.239624,-0.165178,-2.188195,1.131378,-0.038675,-2.148550,1.141412,-0.065655,-2.167212,1.170222,0.035712,-2.006413,1.123037,0.072910,-2.003647,1.242972,0.171211,-2.008178,1.174407,0.209842
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295,0.391235,3.610091,-0.680029,0.420939,3.723048,-0.522073,0.492508,3.671772,-0.444731,0.509057,3.647403,-0.274007,0.607045,3.623129,-0.237214,0.565571,3.635036,-0.159421,0.594191,3.534956,-0.077704,0.726638,3.731414,0.054920,0.702675,3.605570,0.027669
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125,1.928268,10.191718,0.580073,2.037224,10.251148,0.800435,1.985661,10.169394,0.771832,2.104546,10.146700,0.840692,2.168395,10.078571,0.940730,2.238743,10.117877,0.997821,2.199844,10.090683,0.988819,2.306824,10.094959,1.033401,2.320040,10.004197,1.176820

In [10]:
data.to_parquet('umap_embeddings_nntest_260518.parquet')

In [9]:
umaps = pd.read_parquet('embeddings_nntest_260313.parquet')
umaps

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,UMAPnn55-1,UMAPnn55-2,UMAPnn55-3,UMAPnn60-1,UMAPnn60-2,UMAPnn60-3,UMAPnn65-1,UMAPnn65-2,UMAPnn65-3,UMAPnn70-1,UMAPnn70-2,UMAPnn70-3,UMAPnn75-1,UMAPnn75-2,UMAPnn75-3,UMAPnn80-1,UMAPnn80-2,UMAPnn80-3,UMAPnn85-1,UMAPnn85-2,UMAPnn85-3
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011,-0.959336,3.825539,-1.231575,-0.881290,3.796339,-1.209693,-0.870086,3.704909,-0.993322,-0.741683,3.692303,-0.950502,-0.785397,3.743953,-0.928493,-0.760679,3.647432,-0.850287,-0.661774,3.742576,-0.734830
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637,0.806598,6.124864,-1.232763,0.871471,6.029686,-1.179094,0.866591,6.002512,-1.039919,0.968271,5.938120,-1.001814,0.977910,5.954481,-0.898991,0.951395,5.896547,-0.895896,1.066993,5.960493,-0.719571
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847,0.633083,4.132921,10.070456,0.533604,4.124071,10.108575,0.624591,4.132191,10.229904,0.640105,4.060228,10.181063,0.650863,4.067042,10.252739,0.659285,4.106952,10.281441,0.690439,4.038807,10.390600
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585,-1.949973,-0.647341,4.967613,-1.864844,-0.585670,5.083677,-1.807278,-0.580344,5.212979,-1.836826,-0.611205,5.174289,-1.759441,-0.570882,5.230515,-1.715026,-0.590169,5.356193,-1.660230,-0.564810,5.354786
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305,-0.771743,-0.142162,6.456462,-0.777141,-0.047835,6.610816,-0.724739,-0.024433,6.746705,-0.739287,-0.050950,6.726170,-0.718467,-0.017266,6.760951,-0.675153,-0.009987,6.850944,-0.615032,0.017529,6.890368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,-1.475640,-0.103305,2.345048,-1.444229,-0.080627,2.480518,-1.367823,-0.111595,2.604275,-1.315133,-0.139675,2.575526,-1.338057,-0.083955,2.731002,-1.248769,-0.069407,2.771871,-1.231487,-0.086546,2.838809
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779,2.118040,3.065669,8.305524,2.034119,3.145387,8.449854,2.150255,3.124451,8.451149,2.107948,3.061284,8.482687,2.106723,3.110953,8.568293,2.094156,3.141465,8.625670,2.138883,3.119044,8.667297
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,-2.363719,1.229874,-0.350366,-2.225241,1.239624,-0.165178,-2.188195,1.131378,-0.038675,-2.148550,1.141412,-0.065655,-2.167212,1.170222,0.035712,-2.006413,1.123037,0.072910,-2.003647,1.242972,0.171211
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295,0.420939,3.723048,-0.522073,0.492508,3.671772,-0.444731,0.509057,3.647403,-0.274007,0.607045,3.623129,-0.237214,0.565571,3.635036,-0.159421,0.594191,3.534956,-0.077704,0.726638,3.731414,0.054920
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125,2.037224,10.251148,0.800435,1.985661,10.169394,0.771832,2.104546,10.146700,0.840692,2.168395,10.078571,0.940730,2.238743,10.117877,0.997821,2.199844,10.090683,0.988819,2.306824,10.094959,1.033401

In [9]:
splits_soms = umapz2.data_split(photcat=data_soms, speccat=spec95, valid_size=len(spec95), rs=41)
splits_soms.keys()

dict_keys(['valid', 'train_lp', 'test_lp', 'train_spec', 'test_spec'])

In [7]:
# PROCESSING / SPLITS
soms = pd.read_parquet('som_embeddings2M_260409.parquet')
spec_soms = pd.merge(soms.copy()[soms['ID'].isin(spec95['ID'])], spec95[['ID', 'specz']], left_on='ID', right_on='ID', how='left')
splits_soms = umapz2.data_split(photcat=soms, speccat=spec_soms, valid_size=len(spec_soms), rs=41)
valid_soms = copy.deepcopy(splits_soms['valid'])

In [19]:
# PROCESSING / SPLITS
soms = pd.read_parquet('som_rs25_maps.parquet')
spec_soms = pd.merge(soms.copy()[soms['ID'].isin(spec95['ID'])], spec95[['ID', 'specz']], left_on='ID', right_on='ID', how='left')
splits_soms = umapz2.data_split(photcat=soms, speccat=spec_soms, valid_size=len(spec_soms), rs=41)
valid_soms = copy.deepcopy(splits_soms['valid'])

In [ ]:
n_embeddings=25
for i in range(1,n_embeddings+1): 
    map = 'SOMrs'+str(i)
    umapz2.plot_som_valid(full_df=soms, valid_df=splits_soms['valid'], map=map, size=(50,100))

In [ ]:
#sizes=[(50,100)]
#sigmas = [0.5, 1, 2, 4]
#learning_rates = [0.2, 0.4, 0.8, 1.]

sizes=[(46,92), (50,100), (54,108)]
#sizes=[(75,)]

sigmas = [0.85, 1, 1.15]
learning_rates = [0.68, 0.8, 0.92]

for size in sizes:
        n_som_xy = size
        for sigma in sigmas:
            for lr in learning_rates:
                map = 'SOM_'+str(n_som_xy[0])+'_'+str(n_som_xy[1])+'_s'+str(sigma)+'_lr'+str(lr)
                umapz2.plot_som_valid(full_df=soms, valid_df=splits_soms['valid'], 
                                      map=map, size=(8,16))#, 
                                      #filename=map+'_n2M_260407.png');

In [5]:
data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125

In [6]:
# RUN UMAP EMBEDDINGS FOR DIFFERENT RANDOM SEEDS W/ FIXED HYPERPARAMS
n_embeddings = 25

for i in range(n_embeddings):
    print(i)
    embedding_i = umap.UMAP(n_neighbors=70, min_dist=0.0, n_components=3, metric='manhattan', random_state=i, densmap=False).fit(data[['u-g', 'g-r', 'r-i', 'i-z', 'z-y', 'y-J', 'J-H']])
    data['UMAPrs'+str(i)+'-1'] = embedding_i.embedding_[:,0]
    data['UMAPrs'+str(i)+'-2'] = embedding_i.embedding_[:,1]
    data['UMAPrs'+str(i)+'-3'] = embedding_i.embedding_[:,2]

0

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

1

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

2

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

3

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

4

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

5

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

6

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

7

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

8

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

9

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

10

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

11

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

12

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

13

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

14

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

15

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

16

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

17

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

18

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

19

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

20

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

21

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

22

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

23

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

24

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

In [7]:
#data.to_parquet('umap_nn70_rs25_260523.parquet')

In [8]:
print('WOOHOOOOOOOOO!!!')

WOOHOOOOOOOOO!!!

In [12]:
data = pd.read_parquet('df7_maps_250819.parquet')
spec95 = pd.read_parquet('spec95_ugrizyJH_maps_250819.parquet')
data = data.drop(columns=['SOM-1', 'SOM-2', 'UMAP3D-1', 'UMAP3D-2', 'UMAP3D-3'])
spec95 = spec95.drop(columns=['SOM-1', 'SOM-2', 'UMAP3D-1', 'UMAP3D-2', 'UMAP3D-3'])
data = data[~data['ID'].isin(spec95[spec95['specz']<0.01]['ID'])]
spec95 = spec95[spec95['specz']>0.01]
data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125

In [13]:
# loop over n_neighbors hyperparameter arguments (nn_hps) to generate multiple embeddings
nn_hps = [60, 70, 81]

for nn_hp in nn_hps:
    emb_i = umap.UMAP(n_neighbors=nn_hp, min_dist=0.0, metric='manhattan', n_components=3, random_state=41, densmap=False).fit(data[['u-g', 'g-r', 'r-i', 'i-z', 'z-y', 'y-J', 'J-H']])
    data['UMAPnn'+str(nn_hp)+'-1'] = emb_i.embedding_[:,0]
    data['UMAPnn'+str(nn_hp)+'-2'] = emb_i.embedding_[:,1]
    data['UMAPnn'+str(nn_hp)+'-3'] = emb_i.embedding_[:,2]

/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/Applications/anaconda3/envs/env1/lib/python3.11/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

In [14]:
data.to_parquet('umap_nn607081_250819.parquet')

In [15]:
print('WOOOHOOOOO!!!!')

WOOOHOOOOO!!!!

In [16]:
data

,ID,RA,DEC,FLAG_COMBINED,CFHT_u_FLUX,CFHT_u_FLUXERR,CFHT_u_MAGERR,HSC_g_FLUX,HSC_g_FLUXERR,HSC_g_MAGERR,HSC_r_FLUX,HSC_r_FLUXERR,HSC_r_MAGERR,HSC_i_FLUX,HSC_i_FLUXERR,HSC_i_MAGERR,HSC_z_FLUX,HSC_z_FLUXERR,HSC_z_MAGERR,HSC_y_FLUX,HSC_y_FLUXERR,HSC_y_MAGERR,UVISTA_J_FLUX,UVISTA_J_FLUXERR,UVISTA_J_MAGERR,UVISTA_H_FLUX,UVISTA_H_FLUXERR,UVISTA_H_MAGERR,UVISTA_Ks_FLUX,UVISTA_Ks_FLUXERR,UVISTA_Ks_MAGERR,IRAC_CH1_FLUX,IRAC_CH1_FLUXERR,IRAC_CH1_MAGERR,IRAC_CH2_FLUX,IRAC_CH2_FLUXERR,IRAC_CH2_MAGERR,lp_photoz,lp_type,lp_zp_2,lp_NbFilt,lp_zq,lp_model,lp_age,lp_dust,lp_Attenuation,lp_MNUV,lp_MR,lp_MJ,lp_mass_med,lp_mass_med_min68,lp_mass_med_max68,lp_mass_best,lp_SFR_med,lp_sSFR_best,CFHT_u_MAG,HSC_g_MAG,HSC_r_MAG,HSC_i_MAG,HSC_z_MAG,HSC_y_MAG,UVISTA_J_MAG,UVISTA_H_MAG,UVISTA_Ks_MAG,IRAC_CH1_MAG,IRAC_CH2_MAG,u-g,g-r,r-i,i-z,z-y,y-J,J-H,UMAPnn60-1,UMAPnn60-2,UMAPnn60-3,UMAPnn70-1,UMAPnn70-2,UMAPnn70-3,UMAPnn81-1,UMAPnn81-2,UMAPnn81-3
7,12,150.476809,2.331511,0,0.432424,0.006043,0.017385,0.367684,0.004799,0.013929,0.539085,0.006673,0.012705,0.913139,0.006940,0.008187,0.995689,0.010382,0.011179,1.010389,0.021430,0.021652,1.176385,0.018240,0.016771,1.238664,0.023098,0.021265,1.273614,0.031158,0.026693,0.793401,0.012663,0.021113,0.623383,0.011264,0.024039,0.7070,0,NaN,30,0.00,5,9.048000e+08,0.1,1,-17.59872,-18.85507,-18.93651,8.69380,8.65194,8.74706,8.64422,-0.18369,-8.815,24.810225,24.986313,24.570856,23.998658,23.904690,23.888779,23.723626,23.667616,23.637405,24.151268,24.413112,-0.176089,0.415457,0.572198,0.093968,0.015911,0.165153,0.056011,-0.881290,3.796339,-1.209693,-0.741683,3.692303,-0.950502,-0.697438,3.672165,-0.903362
39,73,149.468025,1.625609,0,1.057806,0.006321,0.007477,1.301316,0.007003,0.005769,2.870638,0.011023,0.003954,3.669017,0.012785,0.003763,4.321371,0.018494,0.004597,5.147967,0.045866,0.009110,5.366495,0.022263,0.004492,5.903986,0.031370,0.006063,6.666023,0.046399,0.007598,4.142945,0.036884,0.011779,4.426406,0.054762,0.016462,0.4290,0,NaN,30,0.34,9,1.609000e+09,0.2,1,-17.40718,-19.16920,-19.50800,9.06086,9.01925,9.10800,9.01447,0.08064,-8.977,23.838985,23.614043,22.755054,22.488626,22.310946,22.120911,22.075773,21.972137,21.840333,22.356727,22.284872,0.224942,0.858989,0.266428,0.177680,0.190035,0.045137,0.103637,0.871471,6.029686,-1.179094,0.968271,5.938120,-1.001814,1.027934,5.904968,-0.902367
40,74,150.488035,1.875422,0,0.941051,0.003713,0.004937,1.032136,0.004159,0.004320,1.066959,0.005443,0.005254,1.123350,0.005748,0.005525,1.208387,0.008979,0.007981,1.734654,0.019518,0.011504,2.413042,0.014805,0.006643,2.547439,0.017875,0.008007,2.257407,0.024673,0.011931,2.951406,0.013003,0.005829,3.054308,0.014661,0.006387,1.5087,0,NaN,29,2.23,10,9.048000e+08,0.1,1,-20.37010,-21.24365,-21.42674,9.49598,9.44923,9.54398,9.50023,0.99993,-8.536,23.965967,23.865658,23.829631,23.773713,23.694485,23.301968,22.943588,22.884741,23.015975,22.724928,22.687718,0.100310,0.036027,0.055918,0.079228,0.392517,0.358380,0.058847,0.533604,4.124071,10.108575,0.640105,4.060228,10.181063,0.581099,4.021331,10.299862
46,85,150.476436,2.334178,0,0.685237,0.005227,0.009492,0.669388,0.004202,0.006701,0.744438,0.005884,0.008114,1.119968,0.005803,0.005582,1.484551,0.008772,0.006335,1.619744,0.018884,0.011903,1.782537,0.015855,0.009621,1.867551,0.020190,0.012329,2.274360,0.027033,0.012969,2.573668,0.012908,0.006634,1.992754,0.011691,0.007805,1.0800,0,NaN,29,2.19,5,2.273000e+08,0.2,0,-19.16843,-20.47925,-20.51206,9.14079,9.10236,9.18581,9.12799,0.90000,-8.234,24.310399,24.335805,24.220428,23.776986,23.471012,23.376384,23.272404,23.221819,23.007852,22.873619,23.151366,-0.025406,0.115376,0.443442,0.305974,0.094628,0.103980,0.050585,-1.864844,-0.585670,5.083677,-1.836826,-0.611205,5.174289,-1.713699,-0.614399,5.192638
57,104,149.475722,1.626313,0,0.389645,0.004690,0.015066,0.377765,0.005186,0.014719,0.468260,0.008271,0.018192,0.582758,0.009130,0.016919,1.032440,0.013830,0.014389,1.231677,0.034203,0.028396,1.327044,0.017144,0.013989,1.671119,0.023782,0.016241,1.823997,0.035115,0.021015,2.302721,0.033234,0.019095,2.590386,0.044562,0.022890,1.2817,0,NaN,29,1.01,7,5.709000e+08,0.2,0,-18.94804,-20.47051,-20.73870,9.42859,9.36886,9.49659,9.40345,0.76785,-8.597,24.923327,24.956946,24.723783,24.486279,23.865338,23.673758,23.592787,23.342482,23.247440,22.994396,22.866589,-0.033620,0.233163,0.237504,0.620941,0.191580,0.080971,0.250305,-0.777141,-0.047835,6.610816,-0.739287,-0.050950,6.726170,-0.682928,-0.040629,6.751391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746927,964392,149.926987,2.376219,0,1.002968,0.007177,0.008954,1.022032,0.005433,0.005699,1.378424,0.007239,0.005408,2.395704,0.007750,0.003493,2.969146,0.012144,0.004393,3.190317,0.025382,0.008135,4.197636,0.051640,0.013321,3.960244,0.068713,0.019800,4.311192,0.049579,0.012554,4.892384,0.016271,0.004400,3.330375,0.016820,0.006720,0.8828,0,NaN,28,1.88,6,5.088000e+08,0.2,1,-19.11129,-20.53859,-20.77834,9.33938,9.30075,9.38472,9.34513,0.79998,-8.569,23.896782,23.876339,23.551543,22.951417,22.718421,22.640415,22.342488,22.405695,22.313507,22.176199,22.593767,0.020444,0.324796,0.600126,0.232996,0.078006,0.297927,-0.063207,-1.444229,-0.080627,2.480518,-1.315133,-0.139675,2.575526,-1.234438,-0.092924,2.666580
746931,964398,150.445797,2.041274,0,0.181298,0.005288,0.036389,0.270734,0.003645,0.014400,0.370116,0.004804,0.013344,0.598962,0.005060,0.009111,0.789844,0.008157,0.011083,1.463350,0.017940,0.012525,2.346622,0.013371,0.006166,3.217768,0.017201,0.006098,3.546399,0.024013,0.007390,6.095461,0.013863,0.003009,6.445408,0.014239,0.002939,1.4276,0,NaN,29,1.42,9,2.000000e+09,0.3,1,-18.95152,-21.30856,-22.02227,10.10522,10.06720,10.14134,10.06604,0.91400,-9.135,25.754018,25.318641,24.979156,24.456501,24.156146,23.486630,22.973892,22.631113,22.525531,21.937484,21.876874,0.435377,0.339485,0.522655,0.300355,0.669516,0.512737,0.342779,2.034119,3.145387,8.449854,2.107948,3.061284,8.482687,2.080253,3.088883,8.594171
746932,964399,150.446456,2.041975,0,1.441391,0.007583,0.006564,1.475838,0.005284,0.003829,1.847675,0.006822,0.003796,2.743945,0.007632,0.003000,4.584578,0.012381,0.002898,3.132128,0.025927,0.008457,4.516743,0.019004,0.004553,4.403745,0.024753,0.006412,4.610646,0.034778,0.008232,6.041300,0.015501,0.003394,4.991077,0.016769,0.004470,0.7699,0,NaN,29,1.85,9,1.278000e+08,0.3,0,-19.20053,-20.59380,-20.53390,9.05020,9.01606,9.08420,9.04790,1.30000,-7.731,23.503045,23.477403,23.233436,22.804062,22.246752,22.660401,22.262937,22.290445,22.240596,21.947174,22.154514,0.025642,0.243967,0.429374,0.557310,-0.413649,0.397465,-0.027508,-2.225241,1.239624,-0.165178,-2.148550,1.141412,-0.065655,-2.038897,1.161766,0.047578
746934,964401,150.448750,2.042385,0,0.589872,0.005458,0.011542,0.701791,0.003725,0.005677,1.209010,0.005225,0.004443,1.988288,0.005403,0.002930,2.241010,0.008672,0.004153,2.456919,0.018590,0.007730,3.161674,0.013533,0.004632,3.865762,0.017450,0.005149,4.276106,0.024290,0.006199,NaN,NaN,NaN,NaN,NaN,NaN,0.6936,0,NaN,30,0.51,3,3.602000e+08,0.3,0,-17.99460,-19.79145,-20.19956,9.18869,9.14315,9.23487,9.23363,0.69796,-8.487,24.473106,24.284481,23.693925,23.153802,23.023891,22.924023,22.650207,22.431912,22.322379,NaN,NaN,0.188626,0.590556,0.540123,0.129911,0.099868,0.273816,0.218295,0.492508,3.671772,-0.444731,0.607045,3.623129,-0.237214,0.648045,3.577363,-0.126275
746938,964405,150.444534,2.041696,0,1.226362,0.005562,0.005659,1.846873,0.004103,0.002376,3.094079,0.005558,0.001847,3.508585,0.005615,0.001726,4.561046,0.008984,0.002114,4.162245,0.018875,0.004633,4.977354,0.014083,0.003062,5.314329,0.018188,0.003904,5.596476,0.025448,0.004963,3.167982,0.013983,0.005839,2.750760,0.013866,0.006707,0.3061,0,NaN,30,0.20,5,1.609000e+09,0.1,1,-16.85576,-18.25674,-18.61250,8.65062,8.61218,8.68845,8.60904,-0.36390,-9.075,23.678453,23.233908,22.673671,22.537170,22.252339,22.351681,22.157504,22.086379,22.030213,22.648043,22.801368,0.444545,0.560236,0.136502,0.284831,-0.099342,0.194177,0.071125,1.985661,10.169394,0.771832,2.168395,10.078571,0.940730,2.207379,10.041490,1.037354